name: ros2-foxy-test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: tennis_court
          target-ros2-distro: foxy
